name: Build Docker image
# This workflow is triggered 1st, 16th and 31st
on:
  schedule:
    - cron: '0 0 */15 * *'
  push:
    branches:
      - main
jobs:
  build:
    name: latest
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin   
     - name: Build Docker image
       run: |
        ./compile.sh docker BOARD=arm-64 BRANCH=current RELEASE=hirsute BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,img MAINLINE_MIRROR=google FORCE_USE_RAMDISK=yes WIREGUARD=no USE_CCACHE=yes
        docker tag armbian:$(cat VERSION) armbian/build:main
     - name: Push Docker image
       run: docker push armbian/build:main
