name: Build Docker image
# This workflow is triggered 1st, 16th and 31st
on:
  schedule:
    - cron: '0 0 */15 * *'
  push:
    branches:
      - main
jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  

     - name: Build Docker image
       run: |
        ./compile.sh docker BOARD=arm-64 BRANCH=current RELEASE=hirsute BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,img MAINLINE_MIRROR=google FORCE_USE_RAMDISK=yes WIREGUARD=no USE_CCACHE=yes
        docker tag armbian:$(cat VERSION) armbian-build:main

     - name: Push Docker image
       run: docker push windyoc/armbian-build:main
