name: Build Armbian

on:
#  release:
#    types: published
  push:
    branches:
      - main
  schedule:
    - cron: 0 3 * * 5
#  watch:
#    types: started

#env:
#  RELEASE_SOURCE_TAG: v2017.11
#  BUILD_MINIMAL: yes
#  KERNEL_ONLY: no
#  KERNEL_CONFIGURE: no
#  BOARD: orangepilite
#  BRANCH: next
#  RELEASE: jessie
#  BUILD_DESKTOP: no

jobs:
  build:
    runs-on: debian-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile || echo "no swap,continue!" || exit
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
#        sudo -E apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 0EBFCD88 
#        sudo -E echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
#        sudo -E apt update
#        sudo -E apt install docker-ce -y -qq

    - name: Download source code
      run: |
        git clone -b main --single-branch https://github.com/windyOC/phicomm-n1.git

    - name: Use Cache 
      id: cache-build
      uses: actions/cache@v2
      with:
        path: /var/lib/docker/volumes/armbian*
        key: ${{ runner.os }}-cache-main-${{ steps.date.outputs.date }}
        restore-keys: ${{ runner.os }}-ccache-main-

    - name: Build Armbian
      id: build
      run: |
        cd phicomm-n1
        sudo -E ./compile.sh BOARD=arm-64 BRANCH=current RELEASE=hirsute BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,img MAINLINE_MIRROR=google FORCE_USE_RAMDISK=yes WIREGUARD=no USE_CCACHE=yes
        echo "::set-output name=status::success"
        echo "::set-output name=tag::$(date +"%Y.%m.%d-%H%M")"
        tar c - output/images/*.img | xz -9ev -T0 - > /tmp/Armbian-N1-$(date +"%Y.%m.%d-%H%M").tar.xz 
    #ubuntu release :hiresute(21.04)｜focal(20.04)|bionic(18.04)|xenial(16.04)
    #debian release :bullseye(debian 11)|buster(debian 10)|stretch(debian 9)|jessie(debian 8)

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: steps.build.outputs.status == 'success' && !cancelled()
      with:
        tag_name: Ubuntu-21.04-LTS(Hiresute)-${{ steps.date.outputs.date }}
        files: /tmp/Armbian*
