name: Build Armbian

on:
#  release:
#    types: published
  push:
    branches:
      - main
  schedule:
    - cron: 0 3 * * 5
#  watch:
#    types: started

#env:
#  RELEASE_SOURCE_TAG: v2017.11
#  BUILD_MINIMAL: yes
#  KERNEL_ONLY: no
#  KERNEL_CONFIGURE: no
#  BOARD: orangepilite
#  BRANCH: next
#  RELEASE: jessie
#  BUILD_DESKTOP: no

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile || echo "no swap,continue!" || exit
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
    - name: Download source code
      run: |
        git clone https://github.com/yunsur/phicomm-n1.git
    - name: Build Armbian
      id: build
      run: |
        cd phicomm-n1
        sudo -E ./compile.sh BOARD=arm-64 BRANCH=current RELEASE=buster BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,img FORCE_USE_RAMDISK=yes USE_CCACHE=yes
        echo "::set-output name=status::success"
        tar -zcvf /tmp/Armbian.tar.gz output/images/*.img
    - name: Upload Armbian image
      uses: actions/upload-artifact@master
      if: steps.build.outputs.status == 'success'
      with:
        name: Armbian_firmware
        path: /tmp/Armbian.tar.bz2
